id: AFC166C5C
title: f868E
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:08:43.764350
  last_modified_at: 2022-05-27 19:08:43.764374
